In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
dataset = pd.read_csv('Advertising_data.csv')
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [3]:
X = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, -1].values

In [4]:
dataset.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [5]:
X

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01, 2.80e+04],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state=42)

In [7]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(300, 2)
(100, 2)
(300,)
(100,)


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.svm import SVC

In [10]:
clf = SVC(kernel='linear', random_state=0)
clf.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [11]:
pred = clf.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[61,  2],
       [12, 25]], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.86

In [14]:
from sklearn.model_selection import GridSearchCV

In [16]:
params = [{'C':[1,10,50,100,1000], 'kernel':['linear']},
         {'C':[1,10,50,100,1000], 'kernel':['rbf'], 'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]}]
grid_search = GridSearchCV(estimator=clf,
                    param_grid = params,
                    scoring='accuracy',
                    n_jobs=-1,
                    cv=10
    )

In [17]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=SVC(kernel='linear', random_state=0), n_jobs=-1,
             param_grid=[{'C': [1, 10, 50, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 50, 100, 1000],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
                                    1.0],
                          'kernel': ['rbf']}],
             scoring='accuracy')

In [19]:
grid_search.best_score_

0.9099999999999999

In [20]:
grid_search.best_params_

{'C': 1, 'gamma': 0.7, 'kernel': 'rbf'}

In [22]:
classifier = SVC(C=1.0, kernel='rbf', gamma=0.7)
classifier.fit(X_train, y_train)

SVC(gamma=0.7)

In [23]:
pred = classifier.predict(X_test)

In [24]:
confusion_matrix(y_test, pred)

array([[58,  5],
       [ 1, 36]], dtype=int64)

In [25]:
accuracy_score(y_test, pred)

0.94

In [26]:
#YAAAAAAAYYYYYY!!